### PR TITLE
Added test flow and overrode error handler in helper node

### PR DESCRIPTION
**Pull request by DeanCording**
Mike,

These are the changes needed to initialise a flow so that Catch and Status nodes work.

I also fixed a couple of the sample tests where they weren't closing down the server after they had completed.  It wasn't causing a problem as each new server was starting on a random port, but I'm tracking down a problem that required the server to start on a fixed port which caused problems as earlier tests were leaving the server running on that port.

BTW, do some of the websocket tests fail?

Dean

### CODE REVIEW

**Comment by mblackstock** [comment]
Thanks Dean - will try this out.  The websocket node test included passed for me.  The example tests were all pulled directly from the core Node-RED code.

**Comment by mblackstock** [comment]
for some reason the core node tests I included no longer run for me on this PR.  Before I had 81 tests pass, now, just 1 - websocket-listener.  Do they all run for you when you do an `npm run test`?

**Comment by DeanCording** [comment]
I get everything passing except 

websocket Node
       websocket-listener
         should send:
         should send wholemsg:
         should echo wholemsg:
         should broadcast:

websocket Node
       websocket-client
         should feedback:

**Comment by mblackstock** [comment]
looks like there was an it.only() in the web socket test.  Now they all pass for me again

**Comment by DeanCording** [comment]
Sorry, my bad.   was trying to diagnose the websocket test fails.  I'll fix the PR.

**Comment by mblackstock** [comment]
thanks!  so, just so I understand, you need the tab nodes and 'z' properties for the catch and status nodes to work, but if you don't use those, you don't need them?  Should we make a note on this in the readme?  The core code doesn't have these in the test flows...should they?

**Comment by DeanCording** [comment]
Flows (which match tabs in the editor) create a few behind the scenes links that make things like Catch and Status nodes work.  My opinion is that the nodes should be tested in an environment as close as possible to the production environment as possible, which means setting up the flow/tab and z properties.

I'll foreshadow another PR I'm working on that will allow you to create test flows in the editor and then export them to the clipboard and paste them into the test script.  Exporting from the editor doesn't export the flow descriptor, so the test helper will create one.  I should have it ready later today.

**Comment by mblackstock** [comment]
OK.  Will check it out when you're ready.  I'll probably add some notes
about this on the readme.  If the helper creates the necessary tab and 'z'
nodes, not sure if the tests will need to do that then?

The main repo is now at
https://github.com/node-red/node-red-node-test-helper by the way.  I'll
merge this PR into that, but you may want to fork and do PRs directly from
that repo going forward.

**Comment by DeanCording** [comment]
Actually, hold off on merging that PR with the node-red repository.  I'll send through a combined PR for the next change, which actually overwrites a lot of the changes in this PR.

**Comment by mblackstock** [comment]
ok - will do.

**Pull request merged**
